language: generic
branches:
  only:
    - master
    - loadBalancer
notifications:
  email:
    - bhandar.anuj@gmail.com
    - sagarkrkv@gmail.com

sudo: false

before_deploy:
  - zip -r loadbalancer.zip build-scripts haproxy-config appspec.yml || true
  - mkdir -p "dpl_cd_upload"
  - mv loadbalancer.zip dpl_cd_upload/loadbalancer.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    bucket: spring17-api-gateway-travis-ci
    key: loadbalancer.zip
    region: us-east-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      repo: airavata-courses/spring17-API-Server
      all_branches: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring17-api-gateway-travis-ci
    key: loadbalancer.zip
    bundle_type: zip
    application: spring17-api-gateway-codeDeployApp
    deployment_group: LB-Production
    region: us-east-2
    on:
      repo: airavata-courses/spring17-API-Server
      all_branches: true
    wait-until-deployed: true

after_deploy:
- echo "Performing after deploy procedures..."
