version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  BeforeInstall:
    - location: build-scripts/codeDeployBeforeInstall.sh
  AfterInstall:
    - location: build-scripts/codeDeployInstall.sh
      timeout: 300
runas: root