os: linux
files:
  - source: /
    destination: /home/ec2-user/codeDeploy
hooks:
  BeforeInstall:
    - location: build-scripts/codeDeployBeforeInstall.sh
  AfterInstall:
    - location: build-scripts/codeDeployInstall.sh
      timeout: 300
runas: root
